#cloud-config
hostname: "${hostname}"
power_state:
  delay: now
  mode: reboot
  message: Reboot to apply new hostname
  timeout: 10
users:
  - name: zasda
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    home: /home/zasda
    shell: /bin/bash
    ssh_authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEA41UjOf800AhfaUHudkpp3zfkCqk52TwNE5p2jtgODshJRVgDZBuYKdnDWmDbOH+ftMNFcuYqvOmF0u/KaK3VJLDTBryV5IMM3C+rhIw+q9AucBw/4CCCGV76mua3jfpv053FIAEP1A2yTwJH9DyC4fG3LNMsKwvzWoCNMbSr3FE=
